# Generated by Django 4.1.1 on 2022-09-22 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100, verbose_name='NOMBRES')),
                ('apellidos', models.CharField(max_length=100, verbose_name='APELLIDOS')),
                ('genero', models.CharField(max_length=50, verbose_name='GENERO')),
                ('telefono', models.CharField(max_length=20, verbose_name='TELEFONO')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('email', models.EmailField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=40, verbose_name='especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('especialidad', models.CharField(max_length=40, verbose_name='ESPECIALIDAD')),
                ('fecha_registro', models.DateField(verbose_name='FECHA_REGISTRO')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rol_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol_id', to='hospitalApp.rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
