# Generated by Django 4.1.1 on 2022-09-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_alter_rol_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_id', to='hospitalApp.rol'),
        ),
    ]
