# Generated by Django 4.1.1 on 2022-09-11 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_remove_persona_direccion_remove_persona_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('especialidad', models.CharField(max_length=40, verbose_name='ESPECIALIDAD')),
                ('fecha_registro', models.DateField(verbose_name='FECHA_REGISTRO')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PERSONA_ID', to='hospitalApp.persona')),
            ],
        ),
    ]
