# Generated by Django 4.1.1 on 2022-09-13 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0003_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='id_persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
