# Generated by Django 4.1.1 on 2022-09-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0006_alter_persona_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
