# Generated by Django 4.1.1 on 2022-09-16 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0011_alter_persona_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='persona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_id', to='hospitalApp.persona'),
        ),
    ]
